services:
  - type: web
    name: jimi-plast-api
    runtime: node
    rootDir: jimi-plast/api
    plan: free
    buildCommand: npm install && npx prisma generate && npm run build
    startCommand: npx prisma migrate deploy && npm run prisma:seed && npm run start:prod
    envVars:
      - key: NODE_VERSION
        value: 22.11.0
      - key: DATABASE_URL
        fromDatabase:
          name: jimi-plast-db
          property: connectionString
      - key: JWT_ACCESS_SECRET
        generateValue: true
      - key: WEB_APP_ORIGIN
        value: https://jimi-plast-app.vercel.app
      - key: SEED_ADMIN_EMAIL
        value: admin@jimiplast.dz
      - key: SEED_ADMIN_PASSWORD
        value: ChangeMe123!
      - key: WHATSAPP_CALLMEBOT_PHONE
        sync: false
      - key: WHATSAPP_CALLMEBOT_APIKEY
        sync: false
      - key: GREENAPI_INSTANCE_ID
        sync: false
      - key: GREENAPI_API_TOKEN
        sync: false
      - key: GREENAPI_TARGET_PHONE
        sync: false

databases:
  - name: jimi-plast-db
    plan: free
    databaseName: jimiplast
    user: jimiplast
